# Generated by Django 5.2.17 on 2026-09-16 16:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('executions', '0005_seed_phase4_cutovers'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluatorDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluatorVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_label', models.CharField(max_length=160)),
                ('content_hash', models.CharField(editable=False, max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'Expected a SHA-256 hash.')])),
                ('version', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('method', models.CharField(choices=[('deterministic', 'Deterministic'), ('human', 'Human'), ('model', 'Model'), ('outcome', 'Outcome')], max_length=20)),
                ('implementation', models.CharField(max_length=120)),
                ('rubric', models.JSONField()),
                ('applicability', models.JSONField()),
                ('required_inputs', models.JSONField(default=list)),
                ('aggregation', models.JSONField()),
                ('prompt_manifest', models.JSONField(blank=True, default=list)),
                ('model_configuration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='executions.modelconfiguration')),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='evaluations.evaluatordefinition')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluatorApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_label', models.CharField(max_length=160)),
                ('content_hash', models.CharField(editable=False, max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'Expected a SHA-256 hash.')])),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('superseded', 'Superseded')], max_length=20)),
                ('reason', models.TextField()),
                ('calibration_evidence', models.JSONField(blank=True, default=dict)),
                ('evaluator_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approvals', to='evaluations.evaluatorversion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MetricDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_label', models.CharField(max_length=160)),
                ('content_hash', models.CharField(editable=False, max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'Expected a SHA-256 hash.')])),
                ('key', models.CharField(max_length=100)),
                ('version', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('description', models.TextField()),
                ('unit', models.CharField(max_length=32)),
                ('direction', models.CharField(choices=[('higher', 'Higher'), ('lower', 'Lower'), ('diagnostic', 'Diagnostic')], max_length=16)),
                ('minimum', models.FloatField(blank=True, null=True)),
                ('maximum', models.FloatField(blank=True, null=True)),
                ('aggregation', models.CharField(max_length=80)),
                ('applicability', models.JSONField(default=dict)),
                ('missing_value_policy', models.CharField(default='Report missing separately; never impute a score.', max_length=160)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('key', 'version'), name='eval_metric_key_version'), models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='eval_metric_positive_version'), models.CheckConstraint(condition=models.Q(('minimum__isnull', True), ('maximum__isnull', True), ('maximum__gte', models.F('minimum')), _connector='OR'), name='eval_metric_range')],
            },
        ),
        migrations.AddField(
            model_name='evaluatorversion',
            name='metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evaluations.metricdefinition'),
        ),
        migrations.CreateModel(
            name='EvaluationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_label', models.CharField(max_length=160)),
                ('content_hash', models.CharField(editable=False, max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'Expected a SHA-256 hash.')])),
                ('output_hash', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'Expected a SHA-256 hash.')])),
                ('input_manifest', models.JSONField()),
                ('input_manifest_hash', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'Expected a SHA-256 hash.')])),
                ('criterion_results', models.JSONField(blank=True, default=list)),
                ('summary', models.JSONField()),
                ('progress_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rationale', models.TextField(blank=True)),
                ('idempotency_key', models.CharField(max_length=200, unique=True)),
                ('evaluated_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='executions.llmrun')),
                ('grader_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='graded_evaluations', to='executions.llmrun')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='evaluations.evaluationresult')),
                ('evaluator_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='evaluations.evaluatorversion')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('progress_score__isnull', True), models.Q(('progress_score__gte', 1), ('progress_score__lte', 5)), _connector='OR'), name='eval_progress_one_to_five')],
            },
        ),
        migrations.AddConstraint(
            model_name='evaluatorversion',
            constraint=models.UniqueConstraint(fields=('evaluator', 'version'), name='eval_evaluator_key_version'),
        ),
        migrations.AddConstraint(
            model_name='evaluatorversion',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='eval_version_positive'),
        ),
    ]
