# Generated by Django 5.2.17 on 2026-09-16 22:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0002_immutable_audit_guards'),
        ('executions', '0005_seed_phase4_cutovers'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationExposure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_label', models.CharField(max_length=160)),
                ('content_hash', models.CharField(editable=False, max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'Expected a SHA-256 hash.')])),
                ('actor_user_id', models.PositiveBigIntegerField()),
                ('target_kind', models.CharField(choices=[('research', 'Research'), ('weekly_summary', 'Weekly summary')], max_length=20)),
                ('target_id', models.PositiveBigIntegerField()),
                ('output_hash', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'Expected a SHA-256 hash.')])),
                ('run_output_hash', models.CharField(blank=True, max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'Expected a SHA-256 hash.')])),
                ('source', models.CharField(default='browser', max_length=40)),
                ('idempotency_key', models.CharField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'Expected a SHA-256 hash.')])),
                ('view_session', models.UUIDField()),
                ('producing_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='executions.llmrun')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HumanFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_label', models.CharField(max_length=160)),
                ('content_hash', models.CharField(editable=False, max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'Expected a SHA-256 hash.')])),
                ('actor_user_id', models.PositiveBigIntegerField()),
                ('target_kind', models.CharField(choices=[('research', 'Research'), ('weekly_summary', 'Weekly summary')], max_length=20)),
                ('target_id', models.PositiveBigIntegerField()),
                ('output_hash', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'Expected a SHA-256 hash.')])),
                ('run_output_hash', models.CharField(blank=True, max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'Expected a SHA-256 hash.')])),
                ('source', models.CharField(default='browser', max_length=40)),
                ('idempotency_key', models.CharField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'Expected a SHA-256 hash.')])),
                ('action', models.CharField(choices=[('accept', 'Accept'), ('reject', 'Reject'), ('useful', 'Useful'), ('save', 'Save'), ('cite', 'Cite'), ('action', 'Action'), ('irrelevant', 'Irrelevant'), ('dismiss', 'Dismiss'), ('edit', 'Edit')], max_length=20)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=2000)),
                ('before_hash', models.CharField(blank=True, max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'Expected a SHA-256 hash.')])),
                ('after_hash', models.CharField(blank=True, max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'Expected a SHA-256 hash.')])),
                ('exposure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='evaluations.evaluationexposure')),
                ('producing_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='executions.llmrun')),
                ('supersedes', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='correction', to='evaluations.humanfeedback')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackOutcomeLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_label', models.CharField(max_length=160)),
                ('content_hash', models.CharField(editable=False, max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'Expected a SHA-256 hash.')])),
                ('outcome', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='executions.outcomeevent')),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outcome_links', to='evaluations.humanfeedback')),
            ],
        ),
        migrations.AddConstraint(
            model_name='humanfeedback',
            constraint=models.CheckConstraint(condition=models.Q(('rating__isnull', True), models.Q(('rating__gte', 1), ('rating__lte', 5)), _connector='OR'), name='feedback_rating_one_to_five'),
        ),
        migrations.AddConstraint(
            model_name='feedbackoutcomelink',
            constraint=models.UniqueConstraint(fields=('feedback', 'outcome'), name='feedback_outcome_unique'),
        ),
        migrations.AddIndex(
            model_name='evaluationexposure',
            index=models.Index(fields=['actor_user_id', 'target_kind', 'target_id', 'output_hash', 'created_at'], name='eval_exposure_actor_target'),
        ),
        migrations.AddIndex(
            model_name='humanfeedback',
            index=models.Index(fields=['actor_user_id', 'target_kind', 'target_id', 'output_hash', 'created_at'], name='eval_feedback_actor_target'),
        ),
    ]
