# Generated by Django 5.2.17 on 2026-09-18 20:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0004_interaction_audit_guards'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_label', models.CharField(max_length=160)),
                ('content_hash', models.CharField(editable=False, max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'Expected a SHA-256 hash.')])),
                ('case_key', models.SlugField(max_length=100)),
                ('revision', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('origin', models.JSONField()),
                ('rubric_assignments', models.JSONField()),
                ('cohorts', models.JSONField()),
                ('split', models.CharField(choices=[('development', 'Development'), ('held_out', 'Held out')], max_length=16)),
                ('evidence_cutoff', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('payload_hash', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'Expected a SHA-256 hash.')])),
                ('approval_hash', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'Expected a SHA-256 hash.')])),
                ('idempotency_key', models.CharField(max_length=200, unique=True)),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='evaluations.datasetcase')),
            ],
        ),
        migrations.CreateModel(
            name='DatasetCaseContent',
            fields=[
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='protected_content', serialize=False, to='evaluations.datasetcase')),
                ('payload', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='DatasetCaseTombstone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_label', models.CharField(max_length=160)),
                ('content_hash', models.CharField(editable=False, max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'Expected a SHA-256 hash.')])),
                ('reason', models.CharField(choices=[('expired', 'Expired'), ('required_deletion', 'Required deletion')], max_length=24)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='evaluations.datasetcase')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EvaluationDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_label', models.CharField(max_length=160)),
                ('content_hash', models.CharField(editable=False, max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'Expected a SHA-256 hash.')])),
                ('key', models.SlugField(max_length=100, unique=True)),
                ('purpose', models.CharField(max_length=500)),
                ('owner_user_id', models.PositiveBigIntegerField()),
                ('access_classification', models.CharField(default='restricted', max_length=32)),
                ('eligibility_policy', models.JSONField()),
                ('redaction_policy', models.CharField(max_length=100)),
                ('retention_days', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'permissions': [('operate_datasets', 'Operate protected evaluation datasets')],
                'constraints': [models.CheckConstraint(condition=models.Q(('retention_days__gte', 1)), name='dataset_retention_positive')],
            },
        ),
        migrations.CreateModel(
            name='DatasetSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_label', models.CharField(max_length=160)),
                ('content_hash', models.CharField(editable=False, max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'Expected a SHA-256 hash.')])),
                ('manifest', models.JSONField()),
                ('idempotency_key', models.CharField(max_length=200, unique=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evaluations.evaluationdataset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='datasetcase',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evaluations.evaluationdataset'),
        ),
        migrations.CreateModel(
            name='HumanCalibrationLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_label', models.CharField(max_length=160)),
                ('content_hash', models.CharField(editable=False, max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'Expected a SHA-256 hash.')])),
                ('reviewer_user_id', models.PositiveBigIntegerField()),
                ('criterion_results', models.JSONField()),
                ('progress_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('supporting_refs', models.JSONField(blank=True, default=list)),
                ('adjudicates', models.JSONField(blank=True, default=list)),
                ('idempotency_key', models.CharField(max_length=200, unique=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evaluations.datasetcase')),
                ('evaluator_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evaluations.evaluatorversion')),
            ],
        ),
        migrations.AddConstraint(
            model_name='datasetcase',
            constraint=models.UniqueConstraint(fields=('dataset', 'case_key', 'revision'), name='dataset_case_revision'),
        ),
        migrations.AddConstraint(
            model_name='datasetcase',
            constraint=models.CheckConstraint(condition=models.Q(('revision__gte', 1)), name='dataset_revision_positive'),
        ),
        migrations.AddConstraint(
            model_name='humancalibrationlabel',
            constraint=models.CheckConstraint(condition=models.Q(('progress_score__isnull', True), models.Q(('progress_score__gte', 1), ('progress_score__lte', 5)), _connector='OR'), name='dataset_label_score_range'),
        ),
    ]
