# Generated by Django 5.2.17 on 2026-09-20 22:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0006_dataset_audit_guards'),
        ('executions', '0005_seed_phase4_cutovers'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalibrationPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_label', models.CharField(max_length=160)),
                ('content_hash', models.CharField(editable=False, max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'Expected a SHA-256 hash.')])),
                ('reviewer_ids', models.JSONField()),
                ('thresholds', models.JSONField()),
                ('budget', models.JSONField()),
                ('execution_binding', models.JSONField()),
                ('idempotency_key', models.CharField(max_length=200, unique=True)),
                ('grader_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='model_calibration_plans', to='evaluations.evaluatorversion')),
                ('human_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='human_calibration_plans', to='evaluations.evaluatorversion')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evaluations.datasetsnapshot')),
                ('supersedes', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='evaluations.calibrationplan')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CalibrationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_label', models.CharField(max_length=160)),
                ('content_hash', models.CharField(editable=False, max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'Expected a SHA-256 hash.')])),
                ('request_hash', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'Expected a SHA-256 hash.')])),
                ('reserved_tokens', models.PositiveBigIntegerField()),
                ('reserved_cost_micros', models.PositiveBigIntegerField()),
                ('idempotency_key', models.CharField(max_length=200, unique=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evaluations.datasetcase')),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='executions.llmrun')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evaluations.calibrationplan')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CalibrationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_label', models.CharField(max_length=160)),
                ('content_hash', models.CharField(editable=False, max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'Expected a SHA-256 hash.')])),
                ('input_manifest', models.JSONField()),
                ('metrics', models.JSONField()),
                ('eligible', models.BooleanField(default=False)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evaluations.calibrationplan')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CalibrationReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_label', models.CharField(max_length=160)),
                ('content_hash', models.CharField(editable=False, max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'Expected a SHA-256 hash.')])),
                ('assessment', models.JSONField()),
                ('role', models.CharField(choices=[('independent', 'Independent'), ('adjudication', 'Adjudication')], max_length=16)),
                ('idempotency_key', models.CharField(max_length=200, unique=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evaluations.datasetcase')),
                ('label', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='evaluations.humancalibrationlabel')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evaluations.calibrationplan')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='evaluations.calibrationreview')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CaseEvaluationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_label', models.CharField(max_length=160)),
                ('content_hash', models.CharField(editable=False, max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'Expected a SHA-256 hash.')])),
                ('assessment', models.JSONField()),
                ('summary', models.JSONField()),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='evaluations.calibrationattempt')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
