"""
Django settings for ideaflow project.

Generated by 'django-admin startproject' using Django 5.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from urllib.parse import urlsplit
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Real environment variables win over .env, so deploys can set config without a file.
load_dotenv(BASE_DIR / ".env")


def env_bool(name, default=False):
    return os.getenv(name, str(default)).strip().lower() in {"1", "true", "yes", "on"}


def env_list(name, default=""):
    return [item.strip() for item in os.getenv(name, default).split(",") if item.strip()]


def env_int(name, default=0):
    try:
        return int(os.getenv(name, default))
    except (TypeError, ValueError):
        return default


# SECURITY WARNING: keep the secret key used in production secret!
# No fallback on purpose — a default here would ship as a real deployment's key.
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")
if not SECRET_KEY:
    from django.core.exceptions import ImproperlyConfigured

    raise ImproperlyConfigured(
        "DJANGO_SECRET_KEY is not set. Copy .env.example to .env and fill it in "
        "(see the README for how to generate a key)."
    )

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DJANGO_DEBUG", False)

ALLOWED_HOSTS = env_list("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 'ideas' must come before the allauth apps: Django's template loader
    # returns the first match across INSTALLED_APPS, and ideas/templates/account/
    # overrides allauth's default (unstyled) account templates.
    'ideas',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise serves collected static files in production (right after
    # SecurityMiddleware, per its docs). Harmless in local dev.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ideaflow.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ideaflow.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
#
# DATABASE_URL, e.g. postgres://user:password@localhost:5432/ideaflow — see
# README.md "Using Postgres". Unset, this falls back to the sqlite3 file it
# always used, so existing local setups don't need to change anything.

DATABASES = {
    'default': dj_database_url.parse(
        # dj_database_url.config()'s own `default=` only applies when the env
        # var is absent, not when it's present-but-empty (e.g. `DATABASE_URL=`
        # left blank in .env) — so resolve that fallback explicitly instead.
        os.getenv('DATABASE_URL') or f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

# Store datetimes in UTC (USE_TZ=True) and render them in Pacific Time.
# The IANA zone correctly switches between PST and PDT.
TIME_ZONE = 'America/Los_Angeles'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
# collectstatic gathers everything here for WhiteNoise to serve in production.
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage'
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Auth / Google login (django-allauth)
# https://docs.allauth.org/

SITE_ID = 1

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# The landing page doubles as the login prompt — anonymous visitors hitting a
# @login_required view land there with a "Sign in with Google" button.
LOGIN_URL = '/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

ACCOUNT_ADAPTER = 'ideas.adapters.AccountAdapter'
ACCOUNT_EMAIL_VERIFICATION = 'none'
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*']
ACCOUNT_UNIQUE_EMAIL = True

# Removes the local login/signup/password URLs entirely — Google is the only
# way in. (AccountAdapter/SocialAccountAdapter below are belt-and-suspenders:
# is_open_for_signup still gets consulted internally regardless of routing.)
SOCIALACCOUNT_ONLY = True

SOCIALACCOUNT_ADAPTER = 'ideas.adapters.SocialAccountAdapter'
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': os.getenv('GOOGLE_OAUTH_CLIENT_ID', ''),
            'secret': os.getenv('GOOGLE_OAUTH_CLIENT_SECRET', ''),
            'key': '',
        },
        'SCOPE': ['profile', 'email'],
    },
}


# Agent API (ideas/api.py)
#
# Shared bearer token for the machine-readable /api/ endpoints an external agent
# uses to read ideas and report effort. Empty (the default) disables the API
# entirely, so it stays off until you deliberately set a token.
IDEAFLOW_API_TOKEN = os.getenv('IDEAFLOW_API_TOKEN', '')

# Task -> model routing. Cheap, high-volume work (feed/blog summaries) goes to a
# lighter model; deeper work uses the heavy model. Agents fetch this from
# /api/config and pass the right --model. Override any entry via env.
IDEAFLOW_TASK_MODELS = {
    'summary': os.getenv('IDEAFLOW_MODEL_SUMMARY', 'claude-haiku-4-5'),
    'research': os.getenv('IDEAFLOW_MODEL_RESEARCH', 'claude-opus-4-8'),
    'review': os.getenv('IDEAFLOW_MODEL_REVIEW', 'claude-opus-4-8'),
    'execute': os.getenv('IDEAFLOW_MODEL_EXECUTE', 'claude-opus-4-8'),
    'critique': os.getenv('IDEAFLOW_MODEL_CRITIQUE', 'claude-opus-4-8'),
}

# Semantic graph enrichment. The worker uses OpenAI-compatible JSON endpoints;
# changing embedding models requires a full semantic backfill because vectors
# from different models must never be compared.
IDEAFLOW_SEMANTIC_API_KEY = os.getenv('IDEAFLOW_SEMANTIC_API_KEY', '')
IDEAFLOW_SEMANTIC_API_BASE = os.getenv(
    'IDEAFLOW_SEMANTIC_API_BASE', 'https://api.openai.com/v1'
).rstrip('/')
IDEAFLOW_SEMANTIC_EMBEDDING_MODEL = os.getenv(
    'IDEAFLOW_SEMANTIC_EMBEDDING_MODEL', 'text-embedding-3-small'
)
IDEAFLOW_SEMANTIC_CLASSIFIER_MODEL = os.getenv(
    'IDEAFLOW_SEMANTIC_CLASSIFIER_MODEL', 'gpt-4.1-mini'
)
IDEAFLOW_SEMANTIC_CANDIDATES = env_int('IDEAFLOW_SEMANTIC_CANDIDATES', 12)
IDEAFLOW_SEMANTIC_MIN_SIMILARITY = float(
    os.getenv('IDEAFLOW_SEMANTIC_MIN_SIMILARITY', '0.35')
)

# Isolated Graph Lab. Its static UI is served from a separate browser origin;
# Django issues short-lived read-only capabilities after checking role_graph.
IDEAFLOW_GRAPH_LAB_ENABLED = env_bool('IDEAFLOW_GRAPH_LAB_ENABLED', False)
IDEAFLOW_GRAPH_LAB_ORIGIN = os.getenv(
    'IDEAFLOW_GRAPH_LAB_ORIGIN', 'https://graph-lab.bitesoftheweek.com'
).rstrip('/')
_graph_lab_url = urlsplit(IDEAFLOW_GRAPH_LAB_ORIGIN)
if (
    _graph_lab_url.scheme not in {'http', 'https'}
    or not _graph_lab_url.netloc
    or _graph_lab_url.path
    or _graph_lab_url.query
    or _graph_lab_url.fragment
    or _graph_lab_url.username
    or _graph_lab_url.password
    or IDEAFLOW_GRAPH_LAB_ORIGIN != f'{_graph_lab_url.scheme}://{_graph_lab_url.netloc}'
    or (_graph_lab_url.scheme == 'http' and _graph_lab_url.hostname not in {'localhost', '127.0.0.1'})
):
    raise ValueError('IDEAFLOW_GRAPH_LAB_ORIGIN must be an HTTPS origin without a path.')
IDEAFLOW_GRAPH_CAPABILITY_TTL_SECONDS = max(
    60, min(env_int('IDEAFLOW_GRAPH_CAPABILITY_TTL_SECONDS', 600), 3600)
)
IDEAFLOW_GRAPH_CAPABILITY_MAX_REQUESTS = max(
    1, min(env_int('IDEAFLOW_GRAPH_CAPABILITY_MAX_REQUESTS', 10), 100)
)
IDEAFLOW_GRAPH_EXPORT_MAX_NODES = max(
    1, min(env_int('IDEAFLOW_GRAPH_EXPORT_MAX_NODES', 2000), 10000)
)
IDEAFLOW_GRAPH_EXPORT_MAX_EDGES = max(
    1, min(env_int('IDEAFLOW_GRAPH_EXPORT_MAX_EDGES', 10000), 50000)
)
IDEAFLOW_GRAPH_EXPORT_MAX_BYTES = max(
    1024, min(env_int('IDEAFLOW_GRAPH_EXPORT_MAX_BYTES', 20971520), 52428800)
)
IDEAFLOW_GRAPH_CONTEXT_DEFAULT_TOKEN_BUDGET = max(
    500, env_int('IDEAFLOW_GRAPH_CONTEXT_DEFAULT_TOKEN_BUDGET', 2500)
)
IDEAFLOW_GRAPH_CONTEXT_MAX_TOKEN_BUDGET = max(
    IDEAFLOW_GRAPH_CONTEXT_DEFAULT_TOKEN_BUDGET,
    env_int('IDEAFLOW_GRAPH_CONTEXT_MAX_TOKEN_BUDGET', 8000),
)


# Production hardening (behind nginx + Cloudflare)
#
# nginx terminates TLS and forwards X-Forwarded-Proto, so Django knows the
# original request was HTTPS. CSRF_TRUSTED_ORIGINS must list the real https
# origins (Django 4+ requires the scheme). All env-driven, so local dev over
# http is unaffected.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

CSRF_TRUSTED_ORIGINS = env_list('DJANGO_CSRF_TRUSTED_ORIGINS')

if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # Cloudflare + nginx already redirect http->https; leave SECURE_SSL_REDIRECT
    # off here to avoid redirect loops with a proxy in front.
    SECURE_HSTS_SECONDS = env_int('DJANGO_HSTS_SECONDS', 0)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = SECURE_HSTS_SECONDS > 0
    SECURE_HSTS_PRELOAD = SECURE_HSTS_SECONDS > 0
