# Generated by Django 5.2.16 on 2026-07-20 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
                ('color', models.CharField(default='#44506a', help_text="Hex color for this option's pill, e.g. #24509b.", max_length=7)),
                ('order', models.PositiveIntegerField(default=0, help_text='Position in the dropdown. Lower shows first.')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive options stay on existing ideas but drop out of the dropdown.')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['order', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
                ('color', models.CharField(default='#44506a', help_text="Hex color for this option's pill, e.g. #24509b.", max_length=7)),
                ('order', models.PositiveIntegerField(default=0, help_text='Position in the dropdown. Lower shows first.')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive options stay on existing ideas but drop out of the dropdown.')),
            ],
            options={
                'ordering': ['order', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(blank=True)),
                ('interest_level', models.PositiveSmallIntegerField(choices=[(1, '1 star'), (2, '2 stars'), (3, '3 stars'), (4, '4 stars'), (5, '5 stars')], default=3)),
                ('status', models.CharField(choices=[('current', 'Current'), ('tracking', 'Tracking'), ('archived', 'Archived')], default='current', max_length=16)),
                ('rank', models.PositiveIntegerField(default=0, help_text='Manual ordering within a tab. Lower sorts first.')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ideas', to='ideas.category')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ideas', to='ideas.stage')),
            ],
            options={
                'ordering': ['rank', '-interest_level', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=200)),
                ('url', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='ideas.idea')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
