# Generated by Django 5.2.16 on 2026-07-22 05:54

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_seed_lookups'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
                ('color', models.CharField(default='#44506a', help_text="Hex color for this option's pill, e.g. #24509b.", max_length=7, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$', 'Enter a hex color such as #24509b.')])),
                ('order', models.PositiveIntegerField(default=0, help_text='Position in the dropdown. Lower shows first.')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive options stay on existing ideas but drop out of the dropdown.')),
            ],
            options={
                'verbose_name': 'AI model',
                'ordering': ['order', 'name'],
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(default='#44506a', help_text="Hex color for this option's pill, e.g. #24509b.", max_length=7, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$', 'Enter a hex color such as #24509b.')]),
        ),
        migrations.AlterField(
            model_name='stage',
            name='color',
            field=models.CharField(default='#44506a', help_text="Hex color for this option's pill, e.g. #24509b.", max_length=7, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$', 'Enter a hex color such as #24509b.')]),
        ),
        migrations.CreateModel(
            name='ResearchEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
                ('focus', models.CharField(blank=True, max_length=200)),
                ('context', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the research happened.')),
                ('effort', models.PositiveSmallIntegerField(choices=[(1, '1 star'), (2, '2 stars'), (3, '3 stars'), (4, '4 stars'), (5, '5 stars')], default=3)),
                ('quality', models.PositiveSmallIntegerField(choices=[(1, '1 star'), (2, '2 stars'), (3, '3 stars'), (4, '4 stars'), (5, '5 stars')], default=3)),
                ('tokens_used', models.PositiveIntegerField(blank=True, help_text='Approximate tokens used, if known.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_entries', to='ideas.idea')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='research_entries', to='ideas.aimodel')),
            ],
            options={
                'verbose_name_plural': 'research entries',
                'ordering': ['-occurred_at'],
            },
        ),
    ]
