# Generated by Django 5.2.16 on 2026-07-22 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0004_seed_ai_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_admin', models.BooleanField(default=False, help_text='Full access: Django admin, user management, and every tab.')),
                ('role_current', models.BooleanField(default=False, help_text='View and manage ideas in the Current tab.')),
                ('role_tracking', models.BooleanField(default=False, help_text='View and manage ideas in the Tracking tab.')),
                ('role_archive', models.BooleanField(default=False, help_text='View and manage ideas in the Archive tab.')),
                ('role_add_ideas', models.BooleanField(default=False, help_text='Create new ideas.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
