# Generated by Django 5.2.16 on 2026-08-07 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0005_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500, unique=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive feeds are skipped by refresh_feeds.')),
                ('etag', models.CharField(blank=True, max_length=300)),
                ('last_modified', models.CharField(blank=True, max_length=100)),
                ('last_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ideas', models.ManyToManyField(blank=True, related_name='feeds', to='ideas.idea')),
            ],
            options={
                'ordering': ['title', 'url'],
            },
        ),
        migrations.CreateModel(
            name='FeedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(help_text='Stable per-entry id (feed guid/id, else link).', max_length=500)),
                ('link', models.URLField(blank=True, max_length=500)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('summary', models.TextField(blank=True)),
                ('summarized_at', models.DateTimeField(blank=True, null=True)),
                ('usefulness', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 star'), (2, '2 stars'), (3, '3 stars'), (4, '4 stars'), (5, '5 stars')], help_text="The ingesting agent's 1-5 usefulness rating.", null=True)),
                ('interest', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 star'), (2, '2 stars'), (3, '3 stars'), (4, '4 stars'), (5, '5 stars')], help_text='Your 1-5 personal-interest rating.', null=True)),
                ('info_value', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 star'), (2, '2 stars'), (3, '3 stars'), (4, '4 stars'), (5, '5 stars')], help_text='Your 1-5 information-value rating.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ideas.feed')),
                ('summary_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed_items', to='ideas.aimodel')),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('feed', 'guid'), name='unique_feed_guid')],
            },
        ),
    ]
