# Generated by Django 5.2.16 on 2026-08-08 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0006_feed_feeditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='next_action',
            field=models.TextField(blank=True, help_text='The single next step to take, once the idea has been researched.'),
        ),
    ]
