# Generated by Django 5.2.16 on 2026-08-08 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0007_idea_next_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='is_public',
            field=models.BooleanField(default=False, help_text="Public ideas are listed on the home page and readable by any signed-in user (they still can't edit without the tab's role)."),
        ),
    ]
