# Generated by Django 5.2.16 on 2026-08-09 03:33

import django.db.models.deletion
from django.db import migrations, models


def copy_feed_idea_links(apps, schema_editor):
    """Preserve existing feed↔idea links before the old implicit M2M is removed:
    copy each pair into the new IdeaFeed table (unrated)."""
    Feed = apps.get_model("ideas", "Feed")
    IdeaFeed = apps.get_model("ideas", "IdeaFeed")
    for feed in Feed.objects.all():
        for idea in feed.ideas.all():
            IdeaFeed.objects.get_or_create(feed=feed, idea=idea)


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0008_idea_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_research',
            field=models.BooleanField(default=False, help_text='Research-type categories let their ideas track more feeds (10 instead of 5).'),
        ),
        migrations.AddField(
            model_name='idea',
            name='agent_runs_since_feedback',
            field=models.PositiveIntegerField(default=0, help_text='Agent runs logged since the last human feedback; the idea pauses once it reaches the limit.'),
        ),
        migrations.CreateModel(
            name='IdeaFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 star'), (2, '2 stars'), (3, '3 stars'), (4, '4 stars'), (5, '5 stars')], help_text='How relevant this feed is to this idea (1-5); unrated sorts last.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idea_feeds', to='ideas.feed')),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idea_feeds', to='ideas.idea')),
            ],
            options={
                'ordering': ['-rating', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('idea', 'feed'), name='unique_idea_feed')],
            },
        ),
        # Copy the old links into IdeaFeed, THEN drop the implicit M2M table.
        migrations.RunPython(copy_feed_idea_links, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='feed',
            name='ideas',
        ),
    ]
