# Generated by Django 5.2.16 on 2026-08-09 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0009_remove_feed_ideas_category_is_research_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='feed_limit_override',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Manually cap how many feeds this idea keeps. Leave blank to use the default (5, or 10 for research categories).', null=True),
        ),
    ]
