# Generated by Django 5.2.16 on 2026-08-10 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0010_idea_feed_limit_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Optional parent idea this is a sub-idea of (e.g. Passive Income → a specific SaaS or rental).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='ideas.idea'),
        ),
    ]
