# Generated by Django 5.2.16 on 2026-08-10 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0011_idea_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='proposed_by_agent',
            field=models.BooleanField(default=False, help_text='Created by a research agent (child ideas). Counts toward the per-parent agent child limit.'),
        ),
        migrations.AddField(
            model_name='idea',
            name='suggested_children',
            field=models.TextField(blank=True, help_text="Child ideas an agent suggested for a human to create (used when the agent isn't allowed to create them itself)."),
        ),
    ]
