# Generated by Django 5.2.16 on 2026-08-10 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0012_idea_proposed_by_agent_idea_suggested_children'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='tier',
            field=models.CharField(choices=[('light', 'Light'), ('standard', 'Standard'), ('heavy', 'Heavy')], default='standard', help_text='Rough capability/cost tier, for routing cheap tasks (e.g. summaries) to lighter models.', max_length=10),
        ),
        migrations.AddField(
            model_name='idea',
            name='exec_summary',
            field=models.TextField(blank=True, help_text="Executive summary of the effort's current state (kept up to date by the review agent)."),
        ),
        migrations.AddField(
            model_name='idea',
            name='repo',
            field=models.CharField(blank=True, help_text='Target GitHub repo (owner/name or URL) an agent may branch and open PRs against.', max_length=200),
        ),
    ]
