# Generated by Django 5.2.16 on 2026-08-10 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0013_aimodel_tier_idea_exec_summary_idea_repo'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeditem',
            name='content',
            field=models.TextField(blank=True, help_text='The entry body as published, truncated on ingest. Kept so a scoring agent can judge the item without re-fetching the page.'),
        ),
    ]
