# Generated by Django 5.2.16 on 2026-08-12 23:06

import django.db.models.deletion
from django.db import migrations, models


def migrate_unambiguous_usefulness(apps, schema_editor):
    FeedItem = apps.get_model("ideas", "FeedItem")
    FeedItemAssessment = apps.get_model("ideas", "FeedItemAssessment")
    IdeaFeed = apps.get_model("ideas", "IdeaFeed")
    assessments = []
    for item in FeedItem.objects.exclude(usefulness__isnull=True).iterator():
        idea_ids = list(
            IdeaFeed.objects.filter(feed_id=item.feed_id).values_list(
                "idea_id", flat=True
            )[:2]
        )
        if len(idea_ids) == 1:
            assessments.append(
                FeedItemAssessment(
                    idea_id=idea_ids[0],
                    item_id=item.pk,
                    usefulness=item.usefulness,
                )
            )
    FeedItemAssessment.objects.bulk_create(assessments, ignore_conflicts=True)


def restore_unambiguous_usefulness(apps, schema_editor):
    FeedItem = apps.get_model("ideas", "FeedItem")
    FeedItemAssessment = apps.get_model("ideas", "FeedItemAssessment")
    for item in FeedItem.objects.all().iterator():
        scores = list(
            FeedItemAssessment.objects.filter(item_id=item.pk).values_list(
                "usefulness", flat=True
            )[:2]
        )
        if len(scores) == 1:
            item.usefulness = scores[0]
            item.save(update_fields=["usefulness"])


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0014_feeditem_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedItemAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usefulness', models.PositiveSmallIntegerField(choices=[(1, '1 star'), (2, '2 stars'), (3, '3 stars'), (4, '4 stars'), (5, '5 stars')], help_text='How useful this feed item is to this specific idea (1-5).')),
                ('relevance_note', models.TextField(blank=True, help_text='Optional idea-specific explanation; the global summary stays neutral.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_item_assessments', to='ideas.idea')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='ideas.feeditem')),
            ],
            options={
                'ordering': ['-usefulness', '-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('idea', 'item'), name='unique_idea_feed_item_assessment')],
            },
        ),
        migrations.RunPython(
            migrate_unambiguous_usefulness,
            restore_unambiguous_usefulness,
        ),
        migrations.RemoveField(
            model_name='feeditem',
            name='usefulness',
        ),
    ]
