# Generated by Django 5.2.16 on 2026-08-12 23:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def grant_graph_to_admins(apps, schema_editor):
    Profile = apps.get_model("ideas", "Profile")
    Profile.objects.filter(role_admin=True).update(role_graph=True)


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0015_per_idea_feed_item_assessments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveBigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='role_graph',
            field=models.BooleanField(default=False, help_text='View the knowledge graph.'),
        ),
        migrations.RunPython(grant_graph_to_admins, migrations.RunPython.noop),
        migrations.CreateModel(
            name='IdeaRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('related_to', 'Related to'), ('depends_on', 'Depends on'), ('enables', 'Enables'), ('alternative_to', 'Alternative to'), ('competes_with', 'Competes with'), ('supports', 'Supports'), ('contradicts', 'Contradicts'), ('duplicates', 'Duplicates'), ('inspired_by', 'Inspired by')], max_length=24)),
                ('description', models.TextField(blank=True)),
                ('confidence', models.PositiveSmallIntegerField(choices=[(1, '1 star'), (2, '2 stars'), (3, '3 stars'), (4, '4 stars'), (5, '5 stars')], default=5)),
                ('provenance', models.CharField(choices=[('human', 'Human'), ('agent', 'Agent'), ('imported', 'Imported')], default='human', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idea_relations_created', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relations', to='ideas.idea')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relations', to='ideas.idea')),
            ],
            options={
                'ordering': ['source_id', 'relation_type', 'target_id'],
                'constraints': [models.UniqueConstraint(fields=('source', 'target', 'relation_type'), name='unique_typed_idea_relation'), models.CheckConstraint(condition=models.Q(('source', models.F('target')), _negated=True), name='idea_relation_not_self')],
            },
        ),
    ]
