# Generated by Django 5.2.16 on 2026-08-13 01:09

import django.db.models.deletion
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


def create_vector_index(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute(
            'CREATE INDEX ideas_semantic_embedding_hnsw '
            'ON ideas_ideasemanticstate USING hnsw (embedding vector_cosine_ops) '
            'WITH (m = 16, ef_construction = 64)'
        )


def drop_vector_index(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute('DROP INDEX IF EXISTS ideas_semantic_embedding_hnsw')


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0016_knowledge_graph_foundation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdeaSemanticState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('embedding_model', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('stale', 'Stale'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='stale', max_length=16)),
                ('error', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idea', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='semantic_state', to='ideas.idea')),
            ],
        ),
        migrations.CreateModel(
            name='IdeaRelationSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('related_to', 'Related to'), ('depends_on', 'Depends on'), ('enables', 'Enables'), ('alternative_to', 'Alternative to'), ('competes_with', 'Competes with'), ('supports', 'Supports'), ('contradicts', 'Contradicts'), ('duplicates', 'Duplicates'), ('inspired_by', 'Inspired by')], max_length=24)),
                ('description', models.TextField(blank=True)),
                ('evidence', models.TextField(blank=True)),
                ('confidence', models.FloatField(default=0.5)),
                ('similarity', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('superseded', 'Superseded')], default='pending', max_length=16)),
                ('source_content_hash', models.CharField(max_length=64)),
                ('target_content_hash', models.CharField(max_length=64)),
                ('classifier_model', models.CharField(max_length=100)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_relation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='originating_suggestions', to='ideas.idearelation')),
                ('analyzed_idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semantic_analyses', to='ideas.idea')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relation_suggestions_reviewed', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relation_suggestions', to='ideas.idea')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relation_suggestions', to='ideas.idea')),
            ],
            options={
                'ordering': ['-confidence', '-similarity', 'created_at'],
                'constraints': [models.UniqueConstraint(fields=('source', 'target', 'relation_type'), name='unique_typed_relation_suggestion'), models.CheckConstraint(condition=models.Q(('source', models.F('target')), _negated=True), name='relation_suggestion_not_self')],
            },
        ),
        migrations.RunPython(create_vector_index, drop_vector_index),
    ]
