# Generated by Django 5.2.16 on 2026-08-13 06:36

import django.core.validators
from django.db import migrations, models


def seed_settings(apps, schema_editor):
    apps.get_model('ideas', 'SemanticGraphSettings').objects.get_or_create(
        pk=1, defaults={'auto_accept_confidence_percent': 90}
    )


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0018_graph_lab_capabilities'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemanticGraphSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_accept_confidence_percent', models.PositiveSmallIntegerField(default=90, help_text='Relationships with confidence strictly greater than this percentage are accepted automatically.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Semantic graph settings',
            },
        ),
        migrations.RunPython(seed_settings, migrations.RunPython.noop),
    ]
