# Generated by Django 5.2.16 on 2026-08-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0020_alter_idea_exec_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='backfill_cutoff',
            field=models.DateTimeField(blank=True, help_text='Entries published before this are skipped on every ingest, not just the first. Set once, at creation, to 30 days back.', null=True),
        ),
    ]
