# Generated by Django 5.2.16 on 2026-08-19 03:06

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0036_merge_clean_reviewed_prs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField()),
                ('goals', models.TextField(help_text='Prioritized goals this persona protects.')),
                ('constraints', models.TextField(blank=True, help_text='Decision limits, non-goals, and facts this persona must not invent.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='idea',
            name='last_meaningful_progress_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='idea',
            name='last_persona_review_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='idea',
            name='persona_review_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='idea',
            name='persona_stall_days',
            field=models.PositiveSmallIntegerField(default=14, help_text='Schedule a persona council review after this many days without meaningful progress.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.CreateModel(
            name='IdeaPersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idea_personas', to='ideas.idea')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idea_assignments', to='ideas.persona')),
            ],
            options={
                'ordering': ['persona__name'],
            },
        ),
        migrations.AddField(
            model_name='idea',
            name='personas',
            field=models.ManyToManyField(blank=True, related_name='ideas', through='ideas.IdeaPersona', to='ideas.persona'),
        ),
        migrations.CreateModel(
            name='PersonaReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal', models.JSONField(default=dict)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('consensus', 'Consensus'), ('no_consensus', 'No consensus')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persona_reviews', to='ideas.idea')),
            ],
        ),
        migrations.CreateModel(
            name='PersonaVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject'), ('abstain', 'Abstain')], max_length=8)),
                ('rationale', models.TextField(blank=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ideas.persona')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='ideas.personareview')),
            ],
        ),
        migrations.AddConstraint(
            model_name='ideapersona',
            constraint=models.UniqueConstraint(fields=('idea', 'persona'), name='unique_persona_per_idea'),
        ),
        migrations.AddConstraint(
            model_name='personavote',
            constraint=models.UniqueConstraint(fields=('review', 'persona'), name='unique_persona_vote_per_review'),
        ),
    ]
