# Generated by Django 5.2.16 on 2026-08-19 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0037_persona_councils'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Assign this persona to newly created ideas.'),
        ),
    ]
