# Generated by Django 5.2.16 on 2026-08-19 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0040_persona_agent_prompt'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationshipCouncilReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('no_decision', 'Reviewed — no decision')], max_length=16)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('suggestion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='relationship_council_review', to='ideas.idearelationsuggestion')),
            ],
        ),
        migrations.CreateModel(
            name='RelationshipCouncilVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=16)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('decision', models.CharField(choices=[('accept', 'Accept'), ('reject', 'Reject'), ('abstain', 'Abstain')], max_length=8)),
                ('rationale', models.TextField()),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ideas.persona')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='ideas.relationshipcouncilreview')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('review', 'persona'), name='unique_relationship_council_vote')],
            },
        ),
    ]
