# Generated by Django 5.2.16 on 2026-08-20 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0043_artifact_agent_prompts'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, help_text='Last authenticated request, updated by TrackLastSeenMiddleware. Sessions last two weeks, so this is a better read on activity than last login.', null=True),
        ),
    ]
