# Generated by Django 5.2.16 on 2026-08-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0045_idea_referenced_artifacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='persona_review_paused',
            field=models.BooleanField(default=False, help_text='Manually pause council reviews without disabling the schedule.'),
        ),
    ]
