# Generated by Django 5.2.16 on 2026-08-22 21:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0046_idea_persona_review_paused'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'host-primary'.", max_length=100, unique=True)),
                ('speaker_label', models.CharField(help_text="e.g. 'host' or 'analyst'.", max_length=50)),
                ('reference_audio', models.FileField(blank=True, upload_to='podcast_voices/%Y/%m/')),
                ('reference_text', models.TextField(blank=True, help_text='The exact transcript of reference_audio.')),
                ('mlx_model_repo', models.CharField(blank=True, max_length=200)),
                ('mlx_model_revision', models.CharField(blank=True, max_length=100)),
                ('generation_defaults', models.JSONField(blank=True, default=dict, help_text='Sampling/emotion/speaking-rate/gain defaults for this voice.')),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('slug', models.SlugField(max_length=220)),
                ('episode_number', models.PositiveIntegerField()),
                ('season_number', models.PositiveIntegerField(blank=True, null=True)),
                ('script', models.JSONField(blank=True, default=dict)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('show_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('published', 'Published'), ('unpublished', 'Unpublished')], default='draft', max_length=16)),
                ('audio_file', models.FileField(blank=True, upload_to='podcast_episodes/%Y/%m/')),
                ('audio_checksum_sha256', models.CharField(blank=True, max_length=64)),
                ('audio_mime_type', models.CharField(blank=True, default='audio/mpeg', max_length=100)),
                ('audio_duration_seconds', models.FloatField(blank=True, null=True)),
                ('audio_size_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, help_text='Null for scheduler-created episodes.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('research_entry', models.ForeignKey(blank=True, help_text="The research this episode's script was drawn from.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='podcast_episodes', to='ideas.researchentry')),
            ],
            options={
                'ordering': ['-episode_number'],
            },
        ),
        migrations.CreateModel(
            name='EpisodeRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('researching', 'Researching'), ('script_ready', 'Script ready'), ('awaiting_audio', 'Awaiting audio'), ('rendering', 'Rendering'), ('ready_for_review', 'Ready for review'), ('approved', 'Approved'), ('published', 'Published'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=20)),
                ('worker_id', models.CharField(blank=True, max_length=100)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('manifest', models.JSONField(blank=True, default=dict)),
                ('engine', models.CharField(default='fish-s2-pro', max_length=32)),
                ('model_repo', models.CharField(blank=True, max_length=200)),
                ('model_revision', models.CharField(blank=True, max_length=100)),
                ('rendering_settings', models.JSONField(blank=True, default=dict)),
                ('progress', models.JSONField(blank=True, default=dict, help_text="e.g. {'segments_completed': N, 'segments_total': M}.")),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('error_class', models.CharField(blank=True, max_length=100)),
                ('error_detail', models.TextField(blank=True)),
                ('render_report', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='ideas.episode')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PodcastShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('host_name', models.CharField(blank=True, max_length=200)),
                ('cover_image', models.FileField(blank=True, upload_to='podcast_covers/%Y/%m/')),
                ('language', models.CharField(default='en', max_length=10)),
                ('category', models.CharField(blank=True, help_text="Apple Podcasts category, e.g. 'Technology'.", max_length=100)),
                ('is_explicit', models.BooleanField(default=False)),
                ('default_tts_engine', models.CharField(default='fish-s2-pro', max_length=32)),
                ('target_episode_duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('is_publicly_listed', models.BooleanField(default=False, help_text='Anyone (signed in or not) can reach this show\'s RSS feed and episode pages. No link is ever displayed anywhere — see the plan\'s "do not display the link to the RSS feed" constraint.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idea', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='podcast_show', to='ideas.idea')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='episode',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='ideas.podcastshow'),
        ),
        migrations.AddConstraint(
            model_name='episode',
            constraint=models.UniqueConstraint(fields=('show', 'episode_number'), name='unique_show_episode_number'),
        ),
        migrations.AddConstraint(
            model_name='episode',
            constraint=models.UniqueConstraint(fields=('show', 'slug'), name='unique_show_episode_slug'),
        ),
    ]
