# Generated by Django 5.2.16 on 2026-08-22 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0047_voiceprofile_episode_episoderun_podcastshow_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='episoderun',
            index=models.Index(fields=['status', 'created_at'], name='ideas_episo_status_3f59ba_idx'),
        ),
        migrations.AddIndex(
            model_name='episoderun',
            index=models.Index(fields=['status', 'lease_expires_at'], name='ideas_episo_status_ca6863_idx'),
        ),
    ]
