# Generated by Django 5.2.16 on 2026-08-23 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0048_episoderun_ideas_episo_status_3f59ba_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role_podcast',
            field=models.BooleanField(default=False, help_text='Set up podcast shows, link research sources, and review/publish episodes.'),
        ),
    ]
