# Generated by Django 5.2.16 on 2026-08-24 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0056_cap_podcast_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='repeatresult',
            name='episode',
            field=models.ForeignKey(blank=True, help_text='The podcast episode this candidate was actioned into, if any. Cleared (row deleted) once that episode is published — see Episode.publish().', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repeat_results', to='ideas.episode'),
        ),
    ]
