# Generated by Django 5.2.16 on 2026-08-24 23:54

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0057_repeatresult_episode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repeatresult',
            options={'base_manager_name': 'all_objects', 'ordering': ['-found_at', '-id']},
        ),
        migrations.AlterModelManagers(
            name='repeatresult',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='repeatresult',
            name='unique_repeat_result_url_per_idea',
        ),
        migrations.AddField(
            model_name='repeatresult',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Soft-delete timestamp — set once the episode this was actioned into is published (see Episode.publish()). Deleted rows are excluded everywhere by default; use RepeatResult.all_objects to see them.', null=True),
        ),
        migrations.AddField(
            model_name='repeatresult',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='Who (or which action) triggered the soft delete.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='repeatresult',
            name='episode',
            field=models.ForeignKey(blank=True, help_text='The podcast episode this candidate was actioned into, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repeat_results', to='ideas.episode'),
        ),
        migrations.AddConstraint(
            model_name='repeatresult',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('url', ''), _negated=True), ('deleted_at__isnull', True)), fields=('idea', 'url'), name='unique_repeat_result_url_per_idea'),
        ),
    ]
