# Generated by Django 5.2.17 on 2026-08-31 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executions', '0001_initial'),
        ('ideas', '0058_alter_repeatresult_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='produced_by_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifacts', to='executions.llmrun'),
        ),
        migrations.AddField(
            model_name='episode',
            name='produced_by_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='podcast_episodes', to='executions.llmrun'),
        ),
        migrations.AddField(
            model_name='feeditem',
            name='summarized_by_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='summarized_feed_items', to='executions.llmrun'),
        ),
        migrations.AddField(
            model_name='feeditemassessment',
            name='produced_by_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed_item_assessments', to='executions.llmrun'),
        ),
        migrations.AddField(
            model_name='idearelationsuggestion',
            name='produced_by_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relation_suggestions', to='executions.llmrun'),
        ),
        migrations.AddField(
            model_name='personareview',
            name='produced_by_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persona_reviews', to='executions.llmrun'),
        ),
        migrations.AddField(
            model_name='relationshipcouncilreview',
            name='produced_by_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relationship_council_reviews', to='executions.llmrun'),
        ),
        migrations.AddField(
            model_name='repeatresult',
            name='produced_by_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repeat_results', to='executions.llmrun'),
        ),
        migrations.AddField(
            model_name='researchentry',
            name='produced_by_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_entries', to='executions.llmrun'),
        ),
        migrations.AddField(
            model_name='weeklysummary',
            name='produced_by_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weekly_summaries', to='executions.llmrun'),
        ),
    ]
