# Generated by Django 5.2.17 on 2026-08-31 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executions', '0003_serviceprincipal'),
        ('ideas', '0059_artifact_produced_by_run_episode_produced_by_run_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationshipcouncilvote',
            name='produced_by_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relationship_council_votes', to='executions.llmrun'),
        ),
    ]
