# Generated by Django 5.2.17 on 2026-09-01 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executions', '0004_workflowcutover_artifactversion_deterministicjob_and_more'),
        ('ideas', '0061_seed_relationship_council_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='episoderun',
            name='deterministic_job',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='episode_run', to='executions.deterministicjob'),
        ),
        migrations.AddField(
            model_name='episoderun',
            name='execution_trace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='episode_runs', to='executions.executiontrace'),
        ),
        migrations.AddField(
            model_name='personavote',
            name='produced_by_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persona_votes', to='executions.llmrun'),
        ),
    ]
