from django.urls import path

from . import views
from . import podcast_views

app_name = "ideas"

urlpatterns = [
    path("", views.home, name="home"),
    path("start/", views.start, name="start"),
    # Public podcast pages — no login required. Kept together and clearly
    # marked: nothing anywhere else in the app links to feed.xml (see
    # podcast_views.py's module docstring).
    path("podcast/<slug:show_slug>/feed.xml", podcast_views.PodcastFeed(), name="podcast_feed"),
    path("podcast/<slug:show_slug>/", podcast_views.podcast_show_page, name="podcast_show"),
    path(
        "podcast/<slug:show_slug>/<slug:episode_slug>/",
        podcast_views.podcast_episode_page,
        name="podcast_episode",
    ),
    path(
        "podcast/<slug:show_slug>/<slug:episode_slug>/audio.mp3",
        podcast_views.podcast_episode_audio,
        name="podcast_episode_audio",
    ),
    path("guide/", views.guide, name="guide"),
    path("preferences/", views.preferences, name="preferences"),
    path("help/", views.help_conversation, name="help"),
    path("help/admin/", views.help_admin, name="help_admin"),
    path("help/admin/<int:user_id>/", views.help_admin, name="help_admin_conversation"),
    path("current/", views.current, name="current"),
    path("tracking/", views.tracking, name="tracking"),
    path("archive/", views.archive, name="archive"),
    path("graph/", views.graph, name="graph"),
    path("weekly-summaries/", views.weekly_summaries, name="weekly_summaries"),
    path("daily-report/", views.daily_report, name="daily_report"),
    path("graph-lab/", views.graph_lab, name="graph_lab"),
    path("graph-lab/capability/", views.graph_lab_capability, name="graph_lab_capability"),
    path("graph-lab/export.graphml", views.graph_lab_export, name="graph_lab_export"),
    path("graph/relations/new/", views.graph_relation_create, name="graph_relation_create"),
    path("graph/relations/<int:pk>/delete/", views.graph_relation_delete, name="graph_relation_delete"),
    path("graph/suggestions/<int:pk>/<str:decision>/", views.graph_suggestion_review, name="graph_suggestion_review"),
    path("artifacts/", views.artifacts, name="artifacts"),
    path("feeds/", views.feeds, name="feeds"),
    path("feeds/<int:pk>/rate/", views.rate_feed_item, name="rate_feed_item"),
    path("feeds/ideas/<int:pk>/pause/", views.toggle_feed_ingestion_pause, name="toggle_feed_ingestion_pause"),
    path("new/", views.idea_form, name="create"),
    path("<int:pk>/", views.detail, name="detail"),
    path("<int:pk>/edit/", views.idea_form, name="edit"),
    path("<int:pk>/status/<str:status>/", views.set_status, name="set_status"),
    path("<int:pk>/next-action/", views.set_next_action, name="set_next_action"),
    path(
        "<int:pk>/next-actions/queue/",
        views.queue_next_action,
        name="queue_next_action",
    ),
    path(
        "<int:pk>/repeat-results/<int:result_pk>/",
        views.update_repeat_result,
        name="update_repeat_result",
    ),
    path("<int:pk>/repeat/pause/", views.toggle_repeat_pause, name="toggle_repeat_pause"),
    path("<int:pk>/persona-council/", views.update_persona_council, name="update_persona_council"),
    path(
        "<int:pk>/persona-council/pause/",
        views.toggle_persona_review_pause,
        name="toggle_persona_review_pause",
    ),
    path(
        "<int:pk>/suggested-children/create/",
        views.create_suggested_child,
        name="create_suggested_child",
    ),
    path("<int:pk>/quick-update/", views.quick_update, name="quick_update"),
    path("<int:pk>/research/new/", views.add_research, name="add_research"),
    path(
        "<int:pk>/research/<int:entry_pk>/",
        views.view_research_entry,
        name="view_research_entry",
    ),
    path("<int:pk>/artifacts/new/", views.artifact_form, name="add_artifact"),
    path("<int:pk>/artifacts/summary/", views.request_summary, name="request_summary"),
    path("<int:pk>/artifacts/<int:artifact_pk>/edit/", views.artifact_form, name="edit_artifact"),
    path("<int:pk>/artifacts/<int:artifact_pk>/download/", views.download_artifact, name="download_artifact"),
    path("<int:pk>/artifacts/<int:artifact_pk>/view/", views.view_artifact, name="view_artifact"),
    path("<int:pk>/artifacts/<int:artifact_pk>/delete/", views.delete_artifact, name="delete_artifact"),
    path("<int:pk>/episodes/<int:episode_pk>/", views.episode_review, name="episode_review"),
    path(
        "<int:pk>/episodes/<int:episode_pk>/audio-preview/",
        views.episode_audio_preview,
        name="episode_audio_preview",
    ),
    path("<int:pk>/episodes/<int:episode_pk>/edit/", views.update_episode, name="update_episode"),
    path(
        "<int:pk>/episodes/<int:episode_pk>/approve-publish/",
        views.approve_and_publish_episode,
        name="approve_and_publish_episode",
    ),
    path("<int:pk>/episodes/<int:episode_pk>/reject/", views.reject_episode, name="reject_episode"),
    path("<int:pk>/episodes/<int:episode_pk>/cancel/", views.cancel_episode_run, name="cancel_episode_run"),
    path("<int:pk>/episodes/<int:episode_pk>/regenerate/", views.regenerate_episode, name="regenerate_episode"),
    path("<int:pk>/episodes/<int:episode_pk>/unpublish/", views.unpublish_episode, name="unpublish_episode"),
    path("<int:pk>/episodes/<int:episode_pk>/delete/", views.delete_episode, name="delete_episode"),
    path("<int:pk>/podcast/", views.podcast_show_form, name="podcast_show_form"),
    path("<int:pk>/podcast/sources/", views.add_podcast_source, name="add_podcast_source"),
    path(
        "<int:pk>/podcast/sources/<int:relation_pk>/remove/",
        views.remove_podcast_source,
        name="remove_podcast_source",
    ),
    path(
        "<int:pk>/research/<int:entry_pk>/answers/",
        views.answer_research_questions,
        name="answer_research_questions",
    ),
    path("<int:pk>/continue-work/", views.continue_work, name="continue_work"),
    path("users/", views.user_management, name="user_management"),
    path("ownership/", views.idea_ownership, name="idea_ownership"),
    path("research-history/", views.research_history, name="research_history"),
    path("research-queue/", views.research_queue, name="research_queue"),
    path("ownership/<int:pk>/", views.reassign_idea, name="reassign_idea"),
]
