# Generated by Django 5.2.17 on 2026-08-31 23:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('executions', '0003_serviceprincipal'),
        ('ideas', '0061_seed_relationship_council_prompt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deterministic_score', models.FloatField(default=0.0)),
                ('llm_score', models.FloatField(blank=True, null=True)),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('decision', models.CharField(choices=[('pending', 'Pending'), ('included', 'Included'), ('filtered', 'Filtered'), ('dismissed', 'Dismissed')], default='pending', max_length=16)),
                ('exposed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_candidates', to='ideas.idea')),
                ('scoring_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_candidates', to='executions.llmrun')),
            ],
        ),
        migrations.CreateModel(
            name='EvidenceAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('useful', 'Useful'), ('irrelevant', 'Irrelevant'), ('saved', 'Saved'), ('cited', 'Cited'), ('action_created', 'Action created'), ('dismissed', 'Dismissed')], max_length=24)),
                ('value', models.FloatField(default=1.0)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('attributed_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_actions', to='executions.llmrun')),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_actions', to='ideas.idea')),
                ('legacy_assessment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phase3_action', to='ideas.feeditemassessment')),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='sources.evidencecandidate')),
            ],
        ),
        migrations.CreateModel(
            name='EvidenceExperiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=100, unique=True)),
                ('hypothesis', models.TextField()),
                ('primary_metric', models.CharField(default='useful', max_length=100)),
                ('treatment_percent', models.PositiveSmallIntegerField(default=50)),
                ('salt', models.CharField(max_length=128)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('running', 'Running'), ('paused', 'Paused'), ('completed', 'Completed')], default='draft', max_length=16)),
                ('enrollment_started_at', models.DateTimeField(blank=True, null=True)),
                ('minimum_sample_size', models.PositiveIntegerField(default=100)),
                ('guardrails', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('treatment_percent__lte', 100)), name='evidence_treatment_percent_lte_100')],
            },
        ),
        migrations.CreateModel(
            name='EvidenceAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('randomization_key', models.CharField(max_length=200)),
                ('variant', models.CharField(choices=[('control', 'Control'), ('treatment', 'Treatment')], max_length=16)),
                ('assignment_hash', models.CharField(max_length=64)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='sources.evidencecandidate')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='sources.evidenceexperiment')),
            ],
        ),
        migrations.CreateModel(
            name='EvidenceObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('observed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='sources.evidenceaction')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='sources.evidenceassignment')),
            ],
        ),
        migrations.CreateModel(
            name='LegacyEntitySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=40)),
                ('legacy_id', models.PositiveBigIntegerField()),
                ('content_hash', models.CharField(max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('provenance', models.CharField(default='legacy_import', max_length=40)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('entity_type', 'legacy_id'), name='unique_legacy_entity_snapshot')],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_url', models.URLField(max_length=1000, unique=True)),
                ('kind', models.CharField(choices=[('rss', 'RSS / Atom'), ('web', 'Web'), ('api', 'API')], default='rss', max_length=16)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('fetch_policy', models.JSONField(blank=True, default=dict)),
                ('trust_metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legacy_feed', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phase3_source', to='ideas.feed')),
            ],
            options={
                'ordering': ['title', 'canonical_url'],
            },
        ),
        migrations.CreateModel(
            name='SourceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=500)),
                ('url', models.URLField(blank=True, max_length=1000)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('content_hash', models.CharField(max_length=64)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('ingested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('eligible_for_processing', models.BooleanField(default=True, help_text='False for historical imports so Phase 3 never enqueues the legacy backlog.')),
                ('legacy_feed_item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phase3_source_item', to='ideas.feeditem')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='sources.source')),
            ],
            options={
                'ordering': ['-published_at', '-ingested_at'],
            },
        ),
        migrations.AddField(
            model_name='evidencecandidate',
            name='source_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidates', to='sources.sourceitem'),
        ),
        migrations.AddField(
            model_name='evidenceaction',
            name='source_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='sources.sourceitem'),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent', models.CharField(default='evidence', max_length=120)),
                ('relevance_prior', models.FloatField(default=0.5)),
                ('item_budget', models.PositiveIntegerField(default=25)),
                ('is_paused', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_subscriptions', to='ideas.idea')),
                ('legacy_idea_feed', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phase3_subscription', to='ideas.ideafeed')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='sources.source')),
            ],
        ),
        migrations.AddField(
            model_name='evidencecandidate',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidates', to='sources.subscription'),
        ),
        migrations.AddConstraint(
            model_name='evidenceassignment',
            constraint=models.UniqueConstraint(fields=('experiment', 'randomization_key'), name='sticky_evidence_assignment'),
        ),
        migrations.AddConstraint(
            model_name='evidenceassignment',
            constraint=models.UniqueConstraint(fields=('experiment', 'candidate'), name='unique_experiment_candidate_assignment'),
        ),
        migrations.AddConstraint(
            model_name='evidenceobservation',
            constraint=models.UniqueConstraint(fields=('assignment', 'action'), name='unique_assignment_action_observation'),
        ),
        migrations.AddConstraint(
            model_name='sourceitem',
            constraint=models.UniqueConstraint(fields=('source', 'external_id'), name='unique_source_external_item'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('source', 'idea', 'intent'), name='unique_source_subscription_intent'),
        ),
        migrations.AddConstraint(
            model_name='evidencecandidate',
            constraint=models.UniqueConstraint(fields=('source_item', 'idea'), name='unique_source_item_idea_candidate'),
        ),
    ]
