# Generated by Django 5.2.17 on 2026-08-31 17:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=40)),
                ('model_identifier', models.CharField(max_length=160)),
                ('capability', models.CharField(blank=True, max_length=40)),
                ('settings', models.JSONField(default=dict)),
                ('content_hash', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['provider', 'model_identifier', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='ExecutionTrace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('subject_label', models.CharField(blank=True, max_length=240)),
                ('trigger', models.CharField(max_length=32)),
                ('actor_label', models.CharField(blank=True, max_length=160)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=16)),
                ('correlation_key', models.CharField(blank=True, db_index=True, max_length=160)),
                ('idempotency_key', models.CharField(blank=True, max_length=200)),
                ('experiment_metadata', models.JSONField(blank=True, default=dict)),
                ('queued_at', models.DateTimeField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_traces', to=settings.AUTH_USER_MODEL)),
                ('subject_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LLMRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purpose', models.CharField(choices=[('generation', 'Generation'), ('classification', 'Classification'), ('extraction', 'Extraction'), ('evaluation', 'Evaluation'), ('embedding', 'Embedding')], max_length=20)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('prompt_revision_manifest', models.JSONField(default=list)),
                ('rendered_input_ref', models.CharField(blank=True, max_length=500)),
                ('rendered_input_hash', models.CharField(max_length=64)),
                ('context_manifest', models.JSONField(default=dict)),
                ('output_ref', models.CharField(blank=True, max_length=500)),
                ('output_hash', models.CharField(blank=True, max_length=64)),
                ('parsed_output', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=16)),
                ('finish_reason', models.CharField(blank=True, max_length=80)),
                ('schema_valid', models.BooleanField(null=True)),
                ('provider_request_id', models.CharField(blank=True, db_index=True, max_length=200)),
                ('input_tokens', models.PositiveBigIntegerField(blank=True, null=True)),
                ('output_tokens', models.PositiveBigIntegerField(blank=True, null=True)),
                ('cached_tokens', models.PositiveBigIntegerField(blank=True, null=True)),
                ('reasoning_tokens', models.PositiveBigIntegerField(blank=True, null=True)),
                ('total_tokens', models.PositiveBigIntegerField(blank=True, null=True)),
                ('cost_micros', models.PositiveBigIntegerField(blank=True, null=True)),
                ('cost_currency', models.CharField(default='USD', max_length=3)),
                ('cost_source', models.CharField(blank=True, max_length=24)),
                ('measurement_status', models.CharField(choices=[('complete', 'Complete'), ('partial', 'Partial'), ('unavailable', 'Unavailable')], default='partial', max_length=16)),
                ('measurement_unavailable_reasons', models.JSONField(blank=True, default=list)),
                ('queued_at', models.DateTimeField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('first_token_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_class', models.CharField(blank=True, max_length=160)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('error_detail', models.TextField(blank=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_runs', to='executions.llmrun')),
                ('trace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='executions.executiontrace')),
                ('model_configuration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='executions.modelconfiguration')),
            ],
            options={
                'ordering': ['trace', 'attempt_number', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PricingVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=40)),
                ('model_identifier', models.CharField(max_length=160)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('input_micros_per_million', models.PositiveBigIntegerField(default=0)),
                ('output_micros_per_million', models.PositiveBigIntegerField(default=0)),
                ('cached_micros_per_million', models.PositiveBigIntegerField(default=0)),
                ('reasoning_micros_per_million', models.PositiveBigIntegerField(default=0)),
                ('effective_from', models.DateTimeField()),
                ('effective_until', models.DateTimeField(blank=True, null=True)),
                ('source', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['provider', 'model_identifier', '-effective_from'],
                'constraints': [models.UniqueConstraint(fields=('provider', 'model_identifier', 'effective_from'), name='unique_model_pricing_effective_from')],
            },
        ),
        migrations.AddField(
            model_name='modelconfiguration',
            name='pricing_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='model_configurations', to='executions.pricingversion'),
        ),
        migrations.CreateModel(
            name='ToolInvocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tool_name', models.CharField(max_length=160)),
                ('tool_version', models.CharField(blank=True, max_length=100)),
                ('mutating', models.BooleanField(default=False)),
                ('request_ref', models.CharField(blank=True, max_length=500)),
                ('request_hash', models.CharField(blank=True, max_length=64)),
                ('response_ref', models.CharField(blank=True, max_length=500)),
                ('response_hash', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], max_length=16)),
                ('idempotency_key', models.CharField(blank=True, max_length=200)),
                ('affected_objects', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_class', models.CharField(blank=True, max_length=160)),
                ('error_detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tool_invocations', to='executions.llmrun')),
            ],
            options={
                'ordering': ['started_at', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('approved', 'Approved'), ('superseded', 'Superseded'), ('rejected', 'Rejected')], default='proposed', max_length=16)),
                ('configuration', models.JSONField(default=dict)),
                ('prompt_revision_manifest', models.JSONField(default=list)),
                ('content_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_versions_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_versions_created', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='executions.workflowdefinition')),
            ],
            options={
                'ordering': ['workflow__key', '-version'],
            },
        ),
        migrations.AddField(
            model_name='executiontrace',
            name='workflow_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traces', to='executions.workflowversion'),
        ),
        migrations.CreateModel(
            name='ExecutionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveBigIntegerField()),
                ('event_type', models.CharField(max_length=100)),
                ('occurred_at', models.DateTimeField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='executions.executiontrace')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='executions.llmrun')),
            ],
            options={
                'ordering': ['trace', 'sequence'],
                'constraints': [models.UniqueConstraint(fields=('trace', 'sequence'), name='unique_trace_event_sequence')],
            },
        ),
        migrations.AddConstraint(
            model_name='llmrun',
            constraint=models.UniqueConstraint(fields=('trace', 'attempt_number', 'purpose'), name='unique_trace_attempt_purpose'),
        ),
        migrations.AddConstraint(
            model_name='llmrun',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('trace', 'idempotency_key'), name='unique_run_idempotency_per_trace'),
        ),
        migrations.AddConstraint(
            model_name='toolinvocation',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('run', 'idempotency_key'), name='unique_tool_idempotency_per_run'),
        ),
        migrations.AddConstraint(
            model_name='workflowversion',
            constraint=models.UniqueConstraint(fields=('workflow', 'version'), name='unique_workflow_version'),
        ),
        migrations.AddConstraint(
            model_name='executiontrace',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('workflow_version', 'idempotency_key'), name='unique_workflow_trace_idempotency'),
        ),
    ]
