# Generated by Django 5.2.17 on 2026-09-01 00:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executions', '0003_serviceprincipal'),
        ('ideas', '0061_seed_relationship_council_prompt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowCutover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow_key', models.SlugField(max_length=80, unique=True)),
                ('mode', models.CharField(choices=[('legacy', 'Legacy authoritative'), ('shadow', 'Shadow'), ('authoritative', 'Execution ledger authoritative'), ('frozen', 'Writes frozen')], default='legacy', max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_cutovers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArtifactVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(max_length=120)),
                ('checksum_sha256', models.CharField(max_length=64)),
                ('storage_key', models.CharField(max_length=500)),
                ('source_citations', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artifact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='ideas.artifact')),
                ('episode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='media_versions', to='ideas.episode')),
                ('producing_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='artifact_versions', to='executions.llmrun')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='executions.artifactversion')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('artifact__isnull', False), ('episode__isnull', True)), models.Q(('artifact__isnull', True), ('episode__isnull', False)), _connector='OR'), name='artifact_version_exactly_one_subject')],
            },
        ),
        migrations.CreateModel(
            name='DeterministicJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=60)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=16)),
                ('idempotency_key', models.CharField(blank=True, max_length=200)),
                ('input_hash', models.CharField(blank=True, max_length=64)),
                ('output_hash', models.CharField(blank=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('error_detail', models.TextField(blank=True)),
                ('queued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deterministic_jobs', to='executions.llmrun')),
                ('trace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deterministic_jobs', to='executions.executiontrace')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('kind', 'idempotency_key'), name='unique_deterministic_job_idempotency')],
            },
        ),
        migrations.CreateModel(
            name='OutcomeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=80)),
                ('value', models.FloatField(default=1.0)),
                ('attribution_method', models.CharField(default='direct', max_length=40)),
                ('attribution_confidence', models.FloatField(default=1.0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('idempotency_key', models.CharField(blank=True, max_length=200)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outcome_events', to='ideas.idea')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outcome_events', to='executions.llmrun')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('event_type', 'idempotency_key'), name='unique_outcome_event_idempotency')],
            },
        ),
    ]
